---
# groupsにsudoを指定しないかつappend=trueを抜くとエラいことになる
- name: add to docker group, set zsh as default shell
  user: name=ken groups=ken,docker,sudo append=true shell=/bin/zsh

- name: put /home/ken/.zshrc
  copy: >
    src=roles/user/templates/zshrc
    dest=/home/ken/.zshrc
    owner=ken group=ken
