---
# groupsにsudoを指定しないかつappend=trueを抜くとエラいことになる
- name: add to docker group, set zsh as default shell
  user: name=ken groups=ken,docker,sudo append=true shell=/bin/zsh

- name: put dotfiles
  become: no
  git: >
    repo=https://github.com/endaaman/dotfiles.git
    dest=/home/ken/dotfiles
    version=master
  notify: install dotfiles
