---
- name: get kernel name
  shell: uname -r
  register: kernel_name
  changed_when: false
  always_run: yes

- name: install apt packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - git
    - python
    - python-pip
    - zsh
    - curl
    - wget
    - trash-cli
    - tig
    - nmap
    - ufw
    - bridge-utils
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-virtual
    - linux-image-extra-{{kernel_name.stdout}}
    - docker-engine
    - lxd
    - samba
    - postfix
    - mailutils
    - dovecot-core
    - dovecot-imapd
    - dovecot-pop3d
    - sasl2-bin

- name: install pip packages
  pip: name={{ item }}
  with_items:
    - docker-compose

# - name: get letsencrypt
#   git: >
#     repo=https://github.com/letsencrypt/letsencrypt.git
#     dest=/usr/local/lib/letsencrypt
#     version=master

- include: docker.yml

- include: neovim.yml
