version: '2'

services:
  frontend:
    build: /home/ken/src/github.com/endaaman/frontend
    container_name: endaaman-frontend
    environment:
      - SITE_HOST=endaaman.test
      - SSL=1
      - VIRTUAL_HOST=endaaman.test
    networks:
      - proxy-tier

  backend:
    build: /home/ken/src/github.com/endaaman/backend
    container_name: endaaman-backend
    environment:
      - PASSWORD_HASH
      - SECRET_KEY_BASE
      - VIRTUAL_HOST=api.endaaman.test,static.endaaman.test
    volumes:
      - endaaman-data:/var/www/data
    networks:
      - proxy-tier

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../roles/apps/files/app/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy-tier

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud

  nextcloud-app:
    image: nextcloud:fpm
    container_name: nextcloud-app
    volumes:
      - endaaman-data:/var/www/externals/endaaman
      - nextcloud-app:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    depends_on:
      - nextcloud-db

  nextcloud-web:
    image: nginx
    container_name: nextcloud-web
    volumes:
      - nextcloud-app:/var/www/html:ro
      - ../roles/apps/files/app/nginx-nextcloud.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST=nc.endaaman.test
    depends_on:
      - nextcloud-app
    networks:
      - proxy-tier

volumes:
  nextcloud-db:
  nextcloud-app:
  endaaman-data:

networks:
  proxy-tier:
