url: https://misskey.endaaman.me/

port: 3000

mongodb:
  host: misskey-db
  port: 27017
  db: misskey
  user: misskey
  pass: misskey

redis:
  host: misskey-redis
  port: 6379
  #pass: example-pass

drive:
  storage: 'db'
