nginx-proxy:
  build: /var/apps/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
    - 80:80
    - 443:443
  restart: always

enda:
  extends:
    file: /var/apps/endaaman.me/docker-compose.yml
    service: enda

enda-api:
  extends:
    file: /var/apps/api.endaaman.me/docker-compose.yml
    service: enda-api

enda-static:
  extends:
    file: /var/apps/static.endaaman.me/docker-compose.yml
    service: enda-static

frate:
  extends:
    file: /var/apps/frate-alpine.club/docker-compose.yml
    service: frate
