enda:
  image: endaaman/endaaman.me
  environment:
    VIRTUAL_HOST: endaaman.me,enda.dev
  extra_hosts:
    - 'api.enda.dev:172.17.0.1'
  restart: always

enda-api:
  image: endaaman/api.endaaman.me
  environment:
    VIRTUAL_HOST: api.endaaman.me,api.enda.dev
    SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    DB_HOST: "172.17.0.1"
  volumes:
    - /var/shared/enda:/var/shared/enda
  restart: always

enda-static:
  image: endaaman/static.endaaman.me
  environment:
    VIRTUAL_HOST: static.endaaman.me,static.enda.dev
  volumes:
    - /var/shared/enda:/var/shared/enda
  restart: always

frate:
  extends:
    file: /var/www/frate-alpine.club/docker-compose.yml
    service: frate
  restart: always

nginx-proxy:
  image: endaaman/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /var/certs:/etc/nginx/certs:ro
  ports:
    - 80:80
    - 443:443
  restart: always

