---
- name: install docker compose
  pip: name=docker-compose

- name: mkdir /root/mains
  file: >
    path=/root/main state=directory
    owner=root group=root mode=0755

- name: put docker-compose
  copy: >
    src=roles/docker-compose/templates/docker-compose.yml
    dest=/root/main/docker-compose.yml
    owner=root group=root
  notify: restart docker-compose
