---
# upload dir
- name: mkdir /var/shared/enda
  file: >
    path=/var/shared/enda state=directory
    owner=root group=root mode=0755

- name: put /var/www/docker-compose.yml
  copy: >
    src=roles/apps/files/docker-compose.yml
    dest=/var/www/docker-compose.yml

- name: restart containers
  shell: |
    docker-compose pull && \
    docker-compose up -d --build
  args:
    chdir: /var/www

- name: clean images and containers
  shell: |
    docker images -q -f 'dangling=true' | xargs --no-run-if-empty docker rmi && \
    docker ps -a -q -f 'status=exited' | xargs --no-run-if-empty docker rm -v

