---
# upload dir
- name: mkdir /var/shared/enda
  file: >
    path=/var/shared/enda state=directory
    owner=root group=root mode=0755

- name: put /var/www/docker-compose.yml
  copy: >
    src=roles/apps/templates/docker-compose.yml
    dest=/var/www/docker-compose.yml

- name: put frate-alpine.club
  git: >
    repo=https://github.com/endaaman/frate-alpine.club.git
    dest=/var/www/frate-alpine.club
    version=master

- name: restart containers
  shell: |
    docker-compose pull && \
    docker-compose up -d --build
  args:
    chdir: /var/www
