---
- name: push app dir
  copy: >
    src=roles/apps/files/app
    dest=/var/

- name: restart containers
  shell: |
    docker-compose pull && \
    docker-compose up -d --build
  args:
    chdir: /var/app

- name: clean images and containers
  shell: |
    docker images -q -f 'dangling=true' | xargs --no-run-if-empty docker rmi && \
    docker ps -a -q -f 'status=exited' | xargs --no-run-if-empty docker rm -v
