---
- name: deny all port defaultly
  ufw: state=enabled policy=deny

- name: open tcp ports
  ufw: state=enabled rule=allow proto=tcp port={{ item }}
  with_items:
    - 80
    - 443
    - 4545
    - 139

- name: open udp ports
  ufw: state=enabled rule=allow proto=udp port={{ item }}
  with_items:
    - 137
    - 138

# - name: allow connnection from docker to mariadb
#   ufw: state=enabled rule=allow proto=tcp port=3306 src=172.17.42.1/16

- name: limit port 22
  ufw: state=enabled rule=limit proto=tcp port=22

