---
- include: firewall.yml

- name: put /etc/samba/smb.conf
  copy: >
    src=roles/machine/files/smb.conf
    dest=/etc/samba/smb.conf
  notify: restart samba

- name: mkdir /var/le-certs
  file: >
    path=/var/le-certs state=directory
    owner=root group=root mode=0755

- name: mkdir /var/app
  file: >
    path=/var/app state=directory
    owner=root group=root mode=0755

- name: mkdir /var/shared # refuse to modify shared files
  file: >
    path=/var/shared state=directory
    owner=root group=root mode=1777
