---
- name: deny all port defaultly
  ufw: state=enabled policy=deny

- name: open port 80, 443
  ufw: state=enabled rule=allow proto=tcp port={{ item }}
  with_items:
    - 80
    - 443

- name: allow connnection from docker to mariadb
  ufw: state=enabled rule=allow proto=tcp port=3306 src=172.17.42.1/16

- name: limit port 22
  ufw: state=enabled rule=limit proto=tcp port=22

- name: enable and start mariadb
  service: name=mysql enabled=yes state=started

- name: set auto start docker
  service: name=docker enabled=yes state=started

- name: enable and start cron
  service: name=cron enabled=yes state=started

- name: mkdir /var/certs
  file: >
    path=/var/certs state=directory
    owner=root group=root mode=0755

- name: link ssl cert files
  file: >
    state=link
    src=/etc/letsencrypt/live/{{ item }}/fullchain.pem
    dest=/var/certs/{{ item }}.crt
  with_items:
    - endaaman.me
    - api.endaaman.me
    - static.endaaman.me

- name: link ssl key files
  file: >
    state=link
    src=/etc/letsencrypt/live/{{ item }}/privkey.pem
    dest=/var/certs/{{ item }}.key
  with_items:
    - endaaman.me
    - api.endaaman.me
    - static.endaaman.me

- name: put update-certs.sh
  copy: >
    src=roles/machine/files/update-certs.sh
    dest=/root/update-certs.sh

- name: register update certs script to crontab
  cron: >
    name='update certs'
    minute='20' hour='4' day='20'
    job='bash /root/update-certs.sh'
